# Generated by Django 4.2.6 on 2023-10-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AssetsAndPortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='WebSiteUser',
        ),
    ]
