# Generated by Django 4.2.6 on 2023-11-01 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('PC', 'Steam'), ('PC', 'Epic Games'), ('PC', 'Battle.net'), ('PC', 'GOG'), ('PC', 'Other'), ('Console', 'Playstation'), ('Console', 'Xbox'), ('Console', 'Nintendo'), ('Console', 'Other'), ('Mobile', 'Android'), ('Mobile', 'iOS')], max_length=50)),
            ],
        ),
    ]
