# Generated by Django 4.2.6 on 2023-11-03 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='platform',
            field=models.CharField(choices=[('PC', 'Steam'), ('PC', 'Epic Games'), ('PC', 'Battle.net'), ('PC', 'GOG'), ('Console', 'Playstation'), ('Console', 'Xbox'), ('Console', 'Nintendo'), ('Mobile', 'Android'), ('Mobile', 'iOS')], max_length=50),
        ),
        migrations.CreateModel(
            name='GameLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_library_app.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='GameInLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=50)),
                ('platform', models.CharField(choices=[('PC', 'Steam'), ('PC', 'Epic Games'), ('PC', 'Battle.net'), ('PC', 'GOG'), ('Console', 'Playstation'), ('Console', 'Xbox'), ('Console', 'Nintendo'), ('Mobile', 'Android'), ('Mobile', 'iOS')], max_length=50)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game_library_app.gamelibrary')),
            ],
        ),
    ]
