# Generated by Django 4.2.6 on 2023-11-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_library_app', '0003_gamelibrary_platform_alter_gameinlibrary_platform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameinlibrary',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Strategy', 'Strategy'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Puzzle', 'Puzzle'), ('Idle', 'Idle'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
